default['epel']['centos6']['url_path'] = 'http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm'
default['epel']['centos7']['url_path'] = 'http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm'
default['remi']['centos6']['url_path'] = 'http://rpms.famillecollet.com/enterprise/remi-release-6.rpm'
default['remi']['centos7']['url_path'] = 'http://rpms.famillecollet.com/enterprise/remi-release-7.rpm'
default['rpmforge']['gpg_key'] = 'http://apt.sw.be/RPM-GPG-KEY.dag.txt'
default['rpmforge']['centos6']['url_path'] = 'http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm'
default['rpmforge']['centos7']['url_path'] = 'http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm'
