# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.omnibus.chef_version = :latest
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--ioapic", "on"]
  end

$script = <<SCRIPT
  echo "nameserver 8.8.8.8" > /etc/resolv.conf
  echo "PEERDNS=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
SCRIPT

  config.vm.define :node1 do |node1|
    node1.vm.box = "centos-6.5-x86_64"
    node1.vm.network :private_network, ip: "10.0.0.3"
    node1.ssh.guest_port = 62323
    node1.vm.network :forwarded_port, guest: 62323, host: 2222, id: "ssh", auto_correct: true
    node1.vm.hostname = "node1"
    node1.vm.provision "shell", inline: $script
    node1.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../chef/site-cookbooks/"
      chef.run_list = %w[
        recipe[base]
        recipe[user]
        recipe[ntp]
        recipe[mysql::client]
        recipe[mysql::server]
        recipe[mysql::setup]
        recipe[mysql::conf]
        recipe[mysql-mha::node]
        recipe[sysbench]
      ]
    end
  end

  config.vm.define :node2 do |node2|
    node2.vm.box = "centos-6.5-x86_64"
    node2.vm.network :private_network, ip: "10.0.0.4"
    node2.ssh.guest_port = 62323
    node2.vm.network :forwarded_port, guest: 62323, host: 2222, id: "ssh", auto_correct: true
    node2.vm.hostname = "node2"
    node2.vm.provision "shell", inline: $script
    node2.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../chef/site-cookbooks/"
      chef.run_list = %w[
        recipe[base]
        recipe[user]
        recipe[ntp]
        recipe[mysql::client]
        recipe[mysql::server]
        recipe[mysql::setup]
        recipe[mysql::conf]
        recipe[mysql-mha::node]
        recipe[sysbench]
      ]
    end
  end

   config.vm.define :node3 do |node3|
    node3.vm.box = "centos-6.5-x86_64"
    node3.vm.network :private_network, ip: "10.0.0.5"
    node3.ssh.guest_port = 62323
    node3.vm.network :forwarded_port, guest: 62323, host: 2222, id: "ssh", auto_correct: true
    node3.vm.hostname = "node3"
    node3.vm.provision "shell", inline: $script
    node3.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../chef/site-cookbooks/"
      chef.run_list = %w[
        recipe[base]
        recipe[user]
        recipe[ntp]
        recipe[mysql::client]
        recipe[mysql::server]
        recipe[mysql::setup]
        recipe[mysql::conf]
        recipe[mysql-mha::node]
        recipe[sysbench]
      ]
    end
  end

  config.vm.define :mgmt do |mgmt|
    mgmt.vm.box = "centos-6.5-x86_64"
    mgmt.vm.network :private_network, ip: "10.0.0.6"
    mgmt.ssh.guest_port = 62323
    mgmt.vm.network :forwarded_port, guest: 62323, host: 2222, id: "ssh", auto_correct: true
    mgmt.vm.hostname = "mgmt"
    mgmt.vm.provision "shell", inline: $script
    mgmt.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../chef/site-cookbooks/"
      chef.run_list = %w[
        recipe[base]
        recipe[user]
        recipe[ntp]
        recipe[mysql::client]
        recipe[mysql-mha::manager]
        recipe[sysbench]
      ]
    end
  end

end
